<div class="static-page">
<div class="container p-0">
<h1>Terms Of Use</h1>
<p>Welcome to our shopping site. We provide this site to you subject to the following terms of use (“Terms”). If you visit or shop at this site, you accept these Terms. Please read them carefully.</p>
<h4>Copyright</h4>
<p>All content included on this site, such as text, graphics, logos, button icons and images, is our property or the property of our content suppliers and protected by United States and international copyright laws. All software used on this site is our property or the property of our service provider or its suppliers and protected by United States and international copyright laws.</p>
<h4>License And Site Access</h4>
<p>We grant you a limited license to access and make personal use of this site and not to download (other than page caching) or modify it, or any portion of it, except with our express written consent. This license does not include any resale or commercial use of this site or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of this site or its contents; any downloading or copying of account information for the benefit of another merchant; or any use of data mining, robots, or similar data gathering and extraction tools. This site or any portion of this site may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without our express written consent. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) without our express written consent. You may not use any meta tags or any other “hidden text” utilizing our name or trademarks without our express written consent. Any unauthorized use terminates our permission or license.</p>
<h4>Comments, Communications, And Other Content</h4>
<p>Visitors may submit reviews, suggestions, ideas, comments, questions, or other information, so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of “spam.” You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead to the origin of the content. We reserve the right (but not the obligation) to remove or edit such content.</p>
<p>If you do post content or submit material, and unless we indicate otherwise, you grant us a nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media. You grant us and our sublicensees the right to use the name that you submit in connection with such content, if they choose. You represent and warrant that you own or otherwise control all of the rights to the content that you post; that the content is accurate; that use of the content you supply does not violate this policy and will not cause injury to any person or entity; and that you will indemnify us and Amazon for all claims resulting from content you supply. We have the right but not the obligation to monitor and edit or remove any activity or content. We take no responsibility and assume no liability for any content posted by you or any third party.</p>
<h4>Product Descriptions</h4>
<p>We attempt to be as accurate as possible. However, we do not warrant that product descriptions or other content of this site are accurate, complete, reliable, current, or error-free. If a product is not as described, your sole remedy is to return it in unused condition.</p>
<h4>Disclaimer Of Warranties And Limitation Of Liability</h4>
<p><strong>This site and all information, content, materials, products and services included on or otherwise made available to you through this site are provided on an “as is” and “as available” basis, unless otherwise specified in writing. We make no representations or warranties of any kind, express or implied, as to the operation of this site or the information, content, materials, products or services included on or otherwise made available to you through this site, unless otherwise specified in writing. You expressly agree that your use of this site is at your sole risk.</strong></p>
<p><strong>To the full extent permissible by applicable law, we disclaim all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose. We do not warrant that this site; information, content, materials, products or services included on or otherwise made available to you through this site; their servers; or e-mail sent from us are free of viruses or other harmful components. We will not be liable for any damages of any kind arising from the use of this site or from any information, content, materials, products (including software) or services included on or otherwise made available to you through this site, including, but not limited to direct, indirect, incidental, punitive, and consequential damages, unless otherwise specified in writing.</strong></p>
<p><strong>Certain state laws do not allow limitations on implied warranties or the exclusion or limitation of certain damages. If these laws apply to you, some or all of the above disclaimers, exclusions, or limitations may not apply to you, and you might have additional rights.</strong></p>
<h4>Applicable Law</h4>
<p>By visiting our site, you agree that the laws of the state of Washington, without regard to principles of conflict of laws, will govern these Terms and any dispute of any sort that might arise between us.</p>
<h4>Disputes</h4>
<p>Any dispute relating in any way to your visit to our site or to products or services sold or distributed by us in which the aggregate total claim for relief sought on behalf of one or more parties exceeds $7,500 shall be adjudicated in any state or federal court in New Hanover County, Wilton, and you consent to exclusive jurisdiction and venue in such courts.</p>
<h4>Site Policies, Modification, And Severability</h4>
<p>Please review our other policies, such as our privacy policy, posted on this site. These policies also govern your visit to our site. We reserve the right to make changes to our site, policies, and these Terms at any time. If any of these conditions shall be deemed invalid, void, or for any reason unenforceable, that condition shall be deemed severable and shall not affect the validity and enforceability of any remaining condition.</p>
<h4>Our Address:</h4>
<ul class="static-list-2">
<li>Kaoud Carpets & Rugs</li>
<li>4101 Oleander Dr.</li>
<li>Wilton, CT 28403</li>
<li>Tel: 910-392-2605</li>
</ul>
</div>
</div>